### ISSUE TITLE
Import only import one source

### ISSUE THREAD

**Issue by AbdelsalamHaa** [openvinotoolkit/datumaro#1214] opened 2023-12-01 18:45 UTC
System: 
Windows 11 with WSL 
python 3.8 

##Issue: 
importing the dataset imports only one source of the project, although it might have many sources. 

## Should be 
The import function should import the full project not only one source 

details 
here is my tree/config.yml file 
        `build_targets:
          project:
            parents: []
            stages:
            - hash: ''
              kind: ''
              name: root
              params: {}
              type: project
          task_113:
            parents: []
            stages:
            - hash: ''
              kind: ''
              name: root
              params: {}
              type: source
            - hash: ''
              kind: rename
              name: stage-1
              params:
                regex: '|frame_|task_113_'
              type: transform
            - hash: ''
              kind: random_split
              name: stage-2
              params:
                seed: null
                splits:
                - - train
                  - 0.7
                - - test
                  - 0.3
              type: transform
          task_117:
            parents: []
            stages:
            - hash: ''
              kind: ''
              name: root
              params: {}
              type: source
            - hash: ''
              kind: rename
              name: stage-1
              params:
                regex: '|frame_|task_117_'
              type: transform
            - hash: ''
              kind: random_split
              name: stage-2
              params:
                seed: null
                splits:
                - - train
                  - 0.7
                - - test
                  - 0.3
              type: transform
        format_version: 2
        sources:
          task_113:
            format: yolo
            hash: ''
            options: {}
            path: ''
            url: /home/iradar/aiv_pipeline/datasets/tuna/task_113
          task_117:
            format: yolo
            hash: ''
            options: {}
            path: ''
    url: /home/iradar/aiv_pipeline/datasets/tuna/task_117`

but only task 117 is imported 
 
My code to import
    `dataset_path = '/home/iradar/aiv_pipeline/datasets/tuna'

    dataset = Dataset.import_from(dataset_path, 'yolo') `

**Comment by AbdelsalamHaa** [comment] 2023-12-03 04:13
@vinnamkim 
I just would like to add,  when I used version 1.0.0, the import function worked well and everything seemed fine.

**Comment by vinnamkim** [comment] 2023-12-04 09:08
Hi @AbdelsalamHaa,
Sorry for the late response. It takes time to find the root cause for this. Until we solve this thing, you can merge your datasets manually by code. For example,

```python
from datumaro import Dataset, HLOps

dataset_1 = Dataset.import_from("/home/iradar/aiv_pipeline/datasets/tuna/task_113", 'yolo')
dataset_2 = Dataset.import_from("/home/iradar/aiv_pipeline/datasets/tuna/task_117", 'yolo')
dataset = HLOps.merge([dataset_1, dataset_2])
```

Thank you.

**Comment by wonjuleee** [comment] 2024-02-01 00:36
Thank you @vinnamkim for the kind guidance of Datumaro. I will close this issue.

**Closed as completed by wonjuleee** 2024-02-01 00:36 UTC
