### ISSUE TITLE
Info Needed: Converting annotations using python interface.

### ISSUE THREAD

**Issue by dreaquil** [openvinotoolkit/datumaro#296] opened 2021-06-16 16:07 UTC
Hi! Thanks for the great project alongside CVAT. 

I've had a look around but I'm unable to find documentation about how I would go about converting a dataset using the python interface similar to: 

`datum convert -i annotations.xml -if cvat -f coco_labels`

Can you point me in the right direction?

**Comment by zhiltsov-max** [comment] 2021-06-16 20:36
Hi! Take a look at its source code: https://github.com/openvinotoolkit/datumaro/blob/11484ed3ab52c31f10e7b70ba4065c1cdf943ab0/datumaro/cli/commands/convert.py#L102-L107

There is no function to do it in one call, but it still is not very hard to do:

```python
from datumaro.components.dataset import Dataset

dataset = Dataset.import_from('annotations.xml', 'cvat')
dataset.export('./my_coco_dir', 'coco_labels')
```

**Comment by zhiltsov-max** [comment] 2021-08-17 12:43
I'll close the issue. Feel free to reopen, if the problem is not resolved.

**Closed by zhiltsov-max** 2021-08-17 12:43 UTC
