### ISSUE TITLE
Unable to install datumaro

### ISSUE THREAD

**Issue by sbruneaudubuc** [openvinotoolkit/datumaro#111] opened 2021-02-17 16:58 UTC
I am trying to install datumaro with:

```bash
pip install datumaro
```

But I get the following error message:

```bash
Collecting datumaro
  Using cached datumaro-0.1.5.1-py3-none-any.whl (163 kB)
ERROR: Could not find a version that satisfies the requirement pycocotools-windows; platform_system == "Windows" (from datumaro)
ERROR: No matching distribution found for pycocotools-windows; platform_system == "Windows"
```

I'm on Windows 10

**Comment by sbruneaudubuc** [comment] 2021-02-17 17:14
I 'd like to add that I also tried installing datumaro with the following command (I found this one in a readme file within the archives generated when exporting from CVAT to Datumaro format):

```bash
pip install "git+https://github.com/openvinotoolkit/datumaro"
```

Which resulted in following error message:

```bash
Collecting git+https://github.com/openvinotoolkit/datumaro
  Cloning https://github.com/openvinotoolkit/datumaro to c:\users\admin\appdata\local\temp\pip-req-build-lgezrfk6
ERROR: Could not find a version that satisfies the requirement pycocotools-windows (from datumaro)
ERROR: No matching distribution found for pycocotools-windows
```

**Comment by sbruneaudubuc** [comment] 2021-02-17 20:48
I successfully installed datumaro in linux (ubuntu) so I am guessing that it is simply not supported under Windows. But I would have tought that it would install in WSL which I did not managed to do either...

**Comment by nmanovic** [comment] 2021-02-18 05:17
@sbruneaudubuc , we will investigate the issue.

**Comment by zhiltsov-max** [comment] 2021-02-27 10:50
Hi, which python and pip versions do you use? I was able to install with Win10, python 3.8.6 and pip21.0.1.

**Comment by zhiltsov-max** [comment] 2021-08-13 15:12
Closing, can't reproduce. Windows CI passes.

**Closed by zhiltsov-max** 2021-08-13 15:12 UTC
Labels: bug
