### ISSUE TITLE
Error using datum stats

### ISSUE THREAD

**Issue by Woods1970** [openvinotoolkit/datumaro#873] opened 2023-03-20 20:55 UTC
I have a dataset imported from CVAT using the datumaro data format, and when I run datum stats I get the following error:
AttributeError: 'PointCloud' object has no attribute 'size'

**Comment by vinnamkim** [comment] 2023-03-21 00:31
Hi @Woods1970,
Thanks for your interest on our project!
To reproduce your problem, it will be helpful to us if you provide us a small subset of your dataset.

**Comment by Woods1970** [comment] 2023-03-21 21:02
sure, the datumaro json output for a frame looks like below:the issue seems to be that I'm not using pointclouds, just plain label/bbox pairs.  But for some reason the CVAT datumaro export is pushing out a blank pointcloud field which appears to confusing the datumaro stats function.
{    "id": "12-10-2021a-0000148",    "annotations": [        {            "id": 0,            "type": "bbox",            "attributes": {                "occluded": false,                "rotation": 0.0            },            "group": 0,            "label_id": 4,            "z_order": 0,            "bbox": [                443.9,                508.32,                381.80000000000007,                83.88000000000005            ]        },        {            "id": 0,            "type": "bbox",            "attributes": {                "occluded": false,                "rotation": 0.0            },            "group": 0,            "label_id": 8,            "z_order": 0,            "bbox": [                831.84,                565.11,                8.019999999999982,                15.080000000000041            ]        },        {            "id": 0,            "type": "bbox",            "attributes": {                "occluded": false,                "rotation": 0.0            },            "group": 0,            "label_id": 8,            "z_order": 0,            "bbox": [                176.32,                580.79,                4.700000000000017,                22.710000000000036            ]        },        {            "id": 0,            "type": "bbox",            "attributes": {                "occluded": false,                "rotation": 0.0            },            "group": 0,            "label_id": 8,            "z_order": 0,            "bbox": [                208.62,                592.0,                2.4000000000000057,                9.789999999999964            ]        }    ],    "attr": {        "frame": 5501    },    "point_cloud": {        "path": ""    },    "media": {        "path": ""    }}

    On Tuesday, 21 March 2023 at 00:31:29 GMT, Vinnam Kim ***@***.***> wrote:  
 
 


Hi @Woods1970,
Thanks for your interest on our project!
To reproduce your problem, it will be helpful to us if you provide us a small subset of your dataset.

**Comment by vinnamkim** [comment] 2023-03-22 01:23
@Woods1970 

Thanks for your share! I found that there is `point_cloud` field with empty `path` in your annotation file. To investigate it further, I tried to export my toy dataset to Datumaro format in CVAT as follows.

![image](https://user-images.githubusercontent.com/26541465/226776791-ea6ffe4c-d2e3-477a-8b7f-55626d7cac42.png)

My CVAT version is like this.
![image](https://user-images.githubusercontent.com/26541465/226776945-fe660366-00dd-4170-bc84-80dd3f8218ef.png)

However, I don't find `point_cloud` field in my exported dataset. This is my toy dataset exported to Datumaro format from CVAT: [task_train-2023_03_15_06_48_25-datumaro 1.0.zip](https://github.com/openvinotoolkit/datumaro/files/11035350/task_train-2023_03_15_06_48_25-datumaro.1.0.zip).

Would you let me know your CVAT version and tell us about how you exported your dataset in detail?

**Comment by Woods1970** [comment] 2023-03-22 21:24
Thanks for your continuing help!I'm using a local install of CVAT version 2.4 running in a docker container on Open SUSE Leap.i've tried creating my own toy dataset comprising just two classes (rectangles) and one image, but again the Datumaro 1.0 export contains the point cloud field with no associated data.Maybe this is a feature of version CVAT v2.4?There doesn't seem to be much in the way of options for the export process.  I've tried exporting dataset for the project and separately for a task, but same results.



    On Wednesday, 22 March 2023 at 01:23:24 GMT, Vinnam Kim ***@***.***> wrote:  
 
 


@Woods1970

Thanks for your share! I found that there is point_cloud field with empty path in your annotation file. To investigate it further, I tried to export my toy dataset to Datumaro format in CVAT as follows.



My CVAT version is like this.


However, I don't find point_cloud field in my exported dataset. This is my toy dataset exported to Datumaro format from CVAT: task_train-2023_03_15_06_48_25-datumaro 1.0.zip.

Would you let me know your CVAT version and tell us about how you exported your dataset in detail?

**Comment by vinnamkim** [comment] 2023-03-23 08:06
> Thanks for your continuing help!I'm using a local install of CVAT version 2.4 running in a docker container on Open SUSE Leap.i've tried creating my own toy dataset comprising just two classes (rectangles) and one image, but again the Datumaro 1.0 export contains the point cloud field with no associated data.Maybe this is a feature of version CVAT v2.4?There doesn't seem to be much in the way of options for the export process.  I've tried exporting dataset for the project and separately for a task, but same results. On Wednesday, 22 March 2023 at 01:23:24 GMT, Vinnam Kim ***@***.***> wrote: @Woods1970 Thanks for your share! I found that there is point_cloud field with empty path in your annotation file. To investigate it further, I tried to export my toy dataset to Datumaro format in CVAT as follows. My CVAT version is like this. However, I don't find point_cloud field in my exported dataset. This is my toy dataset exported to Datumaro format from CVAT: task_train-2023_03_15_06_48_25-datumaro 1.0.zip. Would you let me know your CVAT version and tell us about how you exported your dataset in detail? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

I finally succeeded to reproduce your error :sweat_smile:. This is because you export your dataset without `Save images` option: 
![image](https://user-images.githubusercontent.com/26541465/227138861-372c43ec-bac5-4fee-ba53-674f13c6b35c.png)
If I turned off this option, I could get the annotation file with `point_cloud` field as same as yours. I think this is a bug of our project and we will try to fix it. Until that, please turn on `Save images` option from CVAT to solve your problem. Thank you!

**Comment by Woods1970** [comment] 2023-03-23 13:31
ok, thanks.  As a workaround that does work, although in my case exporting the images is a lot of GB :(
    On Thursday, 23 March 2023 at 08:06:51 GMT, Vinnam Kim ***@***.***> wrote:  
 
 



Thanks for your continuing help!I'm using a local install of CVAT version 2.4 running in a docker container on Open SUSE Leap.i've tried creating my own toy dataset comprising just two classes (rectangles) and one image, but again the Datumaro 1.0 export contains the point cloud field with no associated data.Maybe this is a feature of version CVAT v2.4?There doesn't seem to be much in the way of options for the export process.  I've tried exporting dataset for the project and separately for a task, but same results. On Wednesday, 22 March 2023 at 01:23:24 GMT, Vinnam Kim @.> wrote: @Woods1970 Thanks for your share! I found that there is point_cloud field with empty path in your annotation file. To investigate it further, I tried to export my toy dataset to Datumaro format in CVAT as follows. My CVAT version is like this. However, I don't find point_cloud field in my exported dataset. This is my toy dataset exported to Datumaro format from CVAT: task_train-2023_03_15_06_48_25-datumaro 1.0.zip. Would you let me know your CVAT version and tell us about how you exported your dataset in detail? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.>


I finally succeeded to reproduce your error 😅 . This is because you export your dataset without Save images option:

If I turned off this option, I could get the annotation file with point_cloud field as same as yours. I think this is a bug of our project and we will try to fix it. Until that, please turn on Save images option from CVAT to solve your problem. Thanks you!

**Comment by vinnamkim** [comment] 2023-03-24 02:21
Thank you! I'll close this issue. If you have further questions, feel free to open an issue.

**Closed as completed by vinnamkim** 2023-03-24 02:21 UTC
